name: Deploying React Router Shoe Store 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      
      with:
        node-version: 12
    
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    
    - name: Build React App
      run: yarn build
        
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploy to Surge
      run: surge ./build shoe-store-anwar.surge.sh --token ${{ secrets.SECRET_TOKEN_3 }}
